### ISSUE TITLE
Address toolbar without the left margin

### ISSUE THREAD

**Issue by LiuTianXiangP** [GabeVilela/Vivaldi-GX#2]
Due to the latest update, the address bar didn't work as it used to be.
[![image](https://user-images.githubusercontent.com/69110887/92987899-f0f2e500-f4f0-11ea-9134-ede0023cd052.png)
](url)
The address bar takes the space of the sidebar
 
can you update the .css file?

**Comment by GabeVilela** [comment]
That's because they changed some CSS class names.
A fix for that and some other things should be release in future (I can't say when since this is a side project)
Until then, you can replace the old selector, `#main .toolbar.toolbar-addressbar.toolbar-mainbar.toolbar-large` to `div.UrlBar.toolbar.toolbar-mainbar.toolbar-large`

**Comment by LiuTianXiangP** [comment]
That fix solved the issue. Thanks.
