### ISSUE TITLE
Address Bar is WEIRD

### ISSUE THREAD

**Issue by ShadiestGoat** [GabeVilela/Vivaldi-GX#4]
Heya! I love the theme so far, but I am encountering a lot of issues with the address bar. Here is what I have:

![image](https://user-images.githubusercontent.com/48590492/101104762-c8482c00-35c3-11eb-87cc-4987195acebb.png)

First off, there is a lot of free space between the first character and the vivaldi logo. Also, there is space between the logo and the shield icon. 

Second, the text in the adress bar is not centered vertically for some reason.

Next up - It could be me, but i think the x icon isnt centered in the top right. 

Another thing is that the back & reload buttons are overlapping the side bar. I don't think that was supposed to be happenening... 

When hovering your mouse over the current tab, the text either disappears or goes too dark to see. 

Next thing I notice - the icons in the tabs have a redish glow to them, is there a way I can turn that off? 

Is there a way to turn off the zZz on the 'sleeping' tabs?

Thanks in advance ^^

**Comment by GabeVilela** [comment]
>"there is a lot of free space between the first character and the vivaldi logo"
"there is space between the logo and the shield icon"
"the text in the adress bar is not centered vertically for some reason"
"the back & reload buttons are overlapping the side bar"
"the icons in the tabs have a redish glow to them"

Those are already fixed or removed in the dev branch

>"i think the x icon isnt centered in the top right"

I can't fix this, since the window buttons are different in each OS, and I don't own a Win8 machine to test the changes

>Is there a way to turn off the zZz on the 'sleeping' tabs?

You can remove its code snippet. Search for "`$discartedTabsIndicator`"
